In [69]:
import time
import nidaqmx
from nidaqmx.constants import AcquisitionType
from nidaqmx.errors import DaqError
import datetime as dt
import numpy as np

In [70]:
task = nidaqmx.Task()

try:
    with nidaqmx.Task() as task:
        task.ai_channels.add_ai_voltage_chan("cDAQ1Mod2/ai0") # Current Phase A
        task.ai_channels.add_ai_voltage_chan("cDAQ1Mod2/ai1") # Current Phase B
        task.ai_channels.add_ai_voltage_chan("cDAQ1Mod1/ai0") # Voltage Phase A
        task.ai_channels.add_ai_voltage_chan("cDAQ1Mod1/ai2") # Voltage Phase B
        task.timing.cfg_samp_clk_timing(rate=1000, sample_mode=AcquisitionType.CONTINUOUS)
        data = np.array(task.read(number_of_samples_per_channel=1000))
        print(data.T)
        print(type(data))
except DaqError as e:
    print(f"Reading Error: {e}")

task.close()


[[ 1.36329300e-03 -1.03824668e+01 -8.70644800e-03 -1.58858900e-03]
 [ 1.04392100e-03 -1.03824668e+01 -7.11177800e-03 -6.31778000e-04]
 [ 1.36329300e-03 -1.03824668e+01 -7.11177800e-03 -1.26965200e-03]
 ...
 [ 1.36329300e-03 -1.03824668e+01 -7.11177800e-03 -1.26965200e-03]
 [ 1.68266500e-03 -1.03824668e+01 -6.79284400e-03 -6.31778000e-04]
 [ 1.68266500e-03 -1.03824668e+01 -7.43071200e-03 -1.26965200e-03]]
<class 'numpy.ndarray'>


c:\Users\IPMU\anaconda3\envs\devinit\lib\site-packages\nidaqmx\task.py:357: ResourceWarning: Attempted to close NI-DAQmx task of name "_unnamedTask<44B>" but task was already closed.
  'already closed.'.format(self._saved_name), DaqResourceWarning)


In [71]:
save_path = r"C:/Users/IPMU/Desktop/2025-gripper-run3/NIDAQ/"

filename = save_path + dt.datetime.now().strftime("%Y%m%d%H%M%S") + "_NIDAQ_NI9215.csv"
print(filename)

columnname = ['Reltime','Current A','Current B','Voltage A','Voltage B']

try:
    with open(filename, mode="a") as f:
        print(*columnname, sep=", ", file=f)
except:
    pass

C:/Users/IPMU/Desktop/2025-gripper-run3/NIDAQ/20250220145206_NIDAQ_NI9215.csv


In [72]:
StarTime = time.perf_counter()                          
task = nidaqmx.Task()
CTime = 0
SAMPRINGRATE:int = 512

while True:

    #CurrentAbsTime = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    #CurrentRerTime = time.time() - StarTime
    #arr = [CurrentAbsTime, CurrentRerTime]
    try:
        with nidaqmx.Task() as task:
            task.ai_channels.add_ai_voltage_chan("cDAQ1Mod2/ai0") # Current Phase A
            task.ai_channels.add_ai_voltage_chan("cDAQ1Mod2/ai1") # Current Phase B
            task.ai_channels.add_ai_voltage_chan("cDAQ1Mod1/ai0") # Voltage Phase A
            task.ai_channels.add_ai_voltage_chan("cDAQ1Mod1/ai2") # Voltage Phase B
            task.timing.cfg_samp_clk_timing(rate=SAMPRINGRATE, sample_mode=AcquisitionType.CONTINUOUS)
            data = np.array(task.read(number_of_samples_per_channel=SAMPRINGRATE))
    except DaqError as e:
        print(f"Reading Error: {e}")
          
    timedata = np.linspace(0.001+CTime,1+CTime,SAMPRINGRATE)
    arr = np.vstack([timedata,data])
    
    print(arr.T[0])
    print(arr.T[-1])

    try:
        with open(filename, mode="a") as f:
            np.savetxt(f,arr.T,delimiter=",")

    except FileNotFoundError:

        print("FileNotFoundError... :'-(")
        filename = save_path + dt.datetime.now().strftime("%Y%m%d%H%M%S") + ".csv"
        with open(filename, mode="a") as f:
            print(*columnname, sep=", ", file=f)
            print(*arr, sep=", ", file=f)
    
    CTime += 1

[ 1.00000000e-03  1.04392100e-03 -1.03824668e+01 -7.11177800e-03
 -1.58858900e-03]
[ 1.00000000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -1.58858900e-03]
[ 1.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -9.50715000e-04]
[ 2.00000000e+00  1.36329300e-03 -1.03824668e+01 -7.11177800e-03
 -1.26965200e-03]


c:\Users\IPMU\anaconda3\envs\devinit\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<44A>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  DaqResourceWarning
c:\Users\IPMU\anaconda3\envs\devinit\lib\site-packages\nidaqmx\task.py:102: ResourceWarning: Task of name "_unnamedTask<44C>" was not explicitly closed before it was destructed. Resources on the task device may still be reserved.
  DaqResourceWarning


[ 2.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -3.12841000e-04]
[ 3.00000000e+00  1.36329300e-03 -1.03824668e+01 -7.43071200e-03
 -1.26965200e-03]
[ 3.00100000e+00  1.68266500e-03 -1.03824668e+01 -7.43071200e-03
 -1.26965200e-03]
[ 4.00000000e+00  1.36329300e-03 -1.03824668e+01 -7.74964600e-03
 -3.12841000e-04]
[ 4.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -6.31778000e-04]
[ 5.00000000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -1.26965200e-03]
[ 5.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -9.50715000e-04]
[ 6.00000000e+00  1.36329300e-03 -1.03824668e+01 -7.43071200e-03
 -9.50715000e-04]
[ 6.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.11177800e-03
 -9.50715000e-04]
[ 7.00000000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -1.58858900e-03]
[ 7.00100000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -6.31778000e-04]
[ 8.00000000e+00  1.04392100e-03 -1.03824668e+01 -7.43071200e-03
 -3.12841000e-04]
[ 8.

KeyboardInterrupt: 

In [1]:
import lib_NIDAQ
import lib_time
from itertools import islice
import numpy as np

NI9215 = dict()
NI9215["save_path"] = r"C:/Users/IPMU/Desktop/2025-gripper-run3/NIDAQ/"
NI9215["columnnames"] = [
    "Reltime",
    "Current A",
    "Current B",
    "Voltage A",
    "Voltage B",
]
NI9215["filename"] = lib_NIDAQ.create_csv(
    NI9215["save_path"], NI9215["columnnames"]
)

Generated filename: C:/Users/IPMU/Desktop/2025-gripper-run3/NIDAQ/20250221205244_NIDAQ_NI9215.csv


In [ ]:
if __name__ == '__main__':
    # Create a time provider generator instance
    SAMPRINGRATE = 1
    tg = lib_time.time_generator(sampling_rate=SAMPRINGRATE)
    timedata = np.array(list(islice(tg, SAMPRINGRATE)))
    print(timedata)
    lib_NIDAQ.DataAcquisition(tg, NI9215["save_path"], NI9215["filename"], NI9215["columnnames"], sampling_rate=SAMPRINGRATE)

[0.]


KeyboardInterrupt: 

In [ ]:
def daq_NI9215(tg, save_path, filename, columnname, sampling_rate):
     while True:
        timedata = np.array(list(islice(tg, SAMPRINGRATE)))
        lib_NIDAQ.SingleDataAcquisition(timedata, save_path, filename, columnname, sampling_rate)
        


if __name__ == '__main__':
    # Create a time provider generator instance
    SAMPRINGRATE = 1
    tg = lib_time.time_generator(sampling_rate=SAMPRINGRATE)
    #timedata = np.array(list(islice(tg, SAMPRINGRATE)))
    #print(timedata)
    daq_NI9215(tg, NI9215["save_path"], NI9215["filename"], NI9215["columnnames"], sampling_rate=SAMPRINGRATE)
    

KeyboardInterrupt: 